
# Notification hooks - triggered on permission requests and idle timeout
[hooks.notification.tool-permission]
command = "notify-send"
args = ["Claude Code", "Permission needed: {{approval_type}}"]
timeout_ms = 5000
enabled = true

[hooks.notification.general-notify]
command = "$CODEX_PROJECT_DIR/.strategic-claude-basic/core/hooks/notification-hook-codex.py"
timeout_ms = 30000
enabled = true
